In [1]:
# James Roberts - Homework 1 - Problem 6
import numpy as np

In [2]:
def LUFactorization(matrix):
    
    # U starts off as the original matrix
    # (Converted to type float to avoid casting errors)
    U = matrix.copy().astype(float)
    
    # L starts off as an identity matrix
    # and is gradually filled in
    L = np.eye(len(matrix))
    
    # P starts off as an identity matrix
    # and is altered depending on what is needed
    P = np.eye(len(matrix))
    
    # Run a loop for minimum dimension out of the row and column
    for i in range(min(len(matrix), len(matrix[0]))):
        
        # Permutation of rows:
        for j in range(i, len(matrix)):
            # If the current diagonal entry is zero
            if U[i, i] == 0.0:
                # Swap rows with the next down
                # May have to repeat until nonzero first entry is reached
                U[[j, j + 1]] = U[[j + 1, j]]
                
                # Store alteration within the permutation matrix
                P[[j, j + 1]] = P[[j + 1, j]]
            # If current diagonal entry is nonzero, no need to permute
            else: 
                break
                
        # LU Factorization:
        
        # The entries we want to alter are the values below
        # the current diagonal entry
        
        # We want to get an array that contains the multiplier
        # that makes each entry equal the value on the diagonal
        
        # To do this, we divide the entries in the current column
        # excluding the number on the diagonal by the diagonal entry
        multiplier = U[i + 1:, i] / U[i,i]
                
        # Subtract the multiplier values times the current row to make 
        # the matrix have zeros below the current diagonal entry 
        
        # Use the complete row slicing coupled with np.newaxis to 
        # increase the dimension of the multiplier array so that 
        # each row of U can be multiplied by the multiplier
        U[i + 1:,:] -= U[i,:] * multiplier[:, np.newaxis]
        
        # Perform the reverse operation on L so that the arrays multiply 
        # to the original matrix
        L[(i + 1):, i] = multiplier
    
    return P, L, U

In [3]:
# Print LU Factorization
def printLU(mat):
    P, L, U = LUFactorization(mat)
    
    print('Original Matrix:\n',arr)
    print ('P:\n', P, '\nL:\n', L, '\nU:\n', U)
    print('Reconstructed Matrix:\n', P @ L @ U, '\n')

In [4]:
# Testing on smaller matrices

# Standard square matrix
arr = np.array([[2, -2, -3],
                [4, -3, -4],
                [-6, 7, 14]])

printLU(arr)

# More rows than columns
arr = np.array([[0, -2, -3],
                [4, -3, -4],
                [-6, 7, 14],
                [-2, 3, 20]])

printLU(arr)

# More columns than rows
arr = np.array([[0, -2, -3, 4, 5],
                [4, -3, -4, 10, 2],
                [-6, 7, 14, 1, -2],
                [-2, 3, 20, -4, -3]])

printLU(arr)

Original Matrix:
 [[ 2 -2 -3]
 [ 4 -3 -4]
 [-6  7 14]]
P:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 
L:
 [[ 1.  0.  0.]
 [ 2.  1.  0.]
 [-3.  1.  1.]] 
U:
 [[ 2. -2. -3.]
 [ 0.  1.  2.]
 [ 0.  0.  3.]]
Reconstructed Matrix:
 [[ 2. -2. -3.]
 [ 4. -3. -4.]
 [-6.  7. 14.]] 

Original Matrix:
 [[ 0 -2 -3]
 [ 4 -3 -4]
 [-6  7 14]
 [-2  3 20]]
P:
 [[0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 
L:
 [[ 1.          0.          0.          0.        ]
 [ 0.          1.          0.          0.        ]
 [-1.5        -1.25        1.          0.        ]
 [-0.5        -0.75        3.70588235  1.        ]] 
U:
 [[ 4.   -3.   -4.  ]
 [ 0.   -2.   -3.  ]
 [ 0.    0.    4.25]
 [ 0.    0.    0.  ]]
Reconstructed Matrix:
 [[ 0. -2. -3.]
 [ 4. -3. -4.]
 [-6.  7. 14.]
 [-2.  3. 20.]] 

Original Matrix:
 [[ 0 -2 -3  4  5]
 [ 4 -3 -4 10  2]
 [-6  7 14  1 -2]
 [-2  3 20 -4 -3]]
P:
 [[0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 
L:
 [[ 1.          0.          0.          0.        ]
 

In [5]:
# The determinant of the matrix can be calculated by multiplying the diagonal of U

# Tridiagonal matrix:
tridiagonal = np.eye(20) * 2 + np.eye(20, 20, 1) * -1 + np.eye(20, 20, -1) * -1

# Get the LU factorization matrices
P, L, U = LUFactorization(tridiagonal)
print('Determinant:', np.diagonal(U).prod())

# Array B found in problem 4
B = np.array([[2,-1],[1,0]])
print('Check using B matrix from problem 4:',
      (np.linalg.matrix_power(B, 18)@np.array([[3],[2]]))[0])

# Recursive algorithm from problem 4
def triDet(n):
    if n == 1:
        return 2
    if n == 2:
        return 3
    return 2 * triDet(n - 1) - triDet(n - 2)
print('Check recursively:',triDet(20))

print('Check using built in algorithm:',np.linalg.det(tridiagonal))

Determinant: 20.999999999999996
Check using B matrix from problem 4: [21]
Check recursively: 21
Check using built in algorithm: 20.99999999999999


In [6]:
# Credits: 
# https://johnfoster.pge.utexas.edu/numerical-methods-book/LinearAlgebra_LU.html
# I read through this page, which helped to give me a conceptual understanding 
# and flush out my code