In [1]:
import numpy as np

In [2]:
def orthogonalProjection(A):
    U, S, V = np.linalg.svd(A, full_matrices = True)
    
    rank = 0
    for sv in S:
        if (sv > 0):
            rank += 1
    
    U1 = U[:,:rank]
    U1T = np.transpose(U1)
    
    P = np.matmul(U1,U1T)
    
    return P

In [3]:
A = np.array([[1,2,3],[4,5,6],[1,0,8]])
print("A:\n", A)
ortho = orthogonalProjection(A)
print("Orthogonal Proj:\n", ortho)
print(np.matmul(A, ortho).round(10))

A:
 [[1 2 3]
 [4 5 6]
 [1 0 8]]
Orthogonal Proj:
 [[ 1.00000000e+00 -4.00019035e-17  5.73547232e-17]
 [-4.00019035e-17  1.00000000e+00  1.33455078e-16]
 [ 5.73547232e-17  1.33455078e-16  1.00000000e+00]]
[[1. 2. 3.]
 [4. 5. 6.]
 [1. 0. 8.]]


In [12]:
A = np.array([[3,0,0],[0,2,0],[0,0,4], [1,1,1]])
print("A:\n", A)
ortho = orthogonalProjection(A)
print("Orthogonal Proj:\n", ortho)
print(np.matmul(ortho, A).round(10))

A:
 [[3 0 0]
 [0 2 0]
 [0 0 4]
 [1 1 1]]
Orthogonal Proj:
 [[ 0.92195122 -0.11707317 -0.05853659  0.23414634]
 [-0.11707317  0.82439024 -0.08780488  0.35121951]
 [-0.05853659 -0.08780488  0.95609756  0.17560976]
 [ 0.23414634  0.35121951  0.17560976  0.29756098]]
[[ 3.  0.  0.]
 [ 0.  2. -0.]
 [ 0. -0.  4.]
 [ 1.  1.  1.]]


In [13]:
A = np.random.rand(12, 10)
print("A:\n", A)
ortho = orthogonalProjection(A)
print("Orthogonal Proj:\n", ortho)
print(np.matmul(ortho, A).round(10))

A:
 [[0.50757888 0.32536604 0.02036776 0.56893183 0.37573565 0.87954686
  0.95810182 0.74254128 0.34202914 0.2121006 ]
 [0.41331325 0.40002838 0.88351684 0.56003887 0.53420872 0.93787189
  0.20604667 0.48552504 0.49908134 0.90351039]
 [0.77395282 0.89232772 0.25428242 0.14580041 0.79091369 0.58132385
  0.00775092 0.96495486 0.71952481 0.19134746]
 [0.76011517 0.78476818 0.37962593 0.17479717 0.01163743 0.29678962
  0.40503027 0.44560705 0.02317367 0.47450735]
 [0.09853563 0.92075249 0.0829527  0.97598359 0.33136741 0.64128593
  0.00698732 0.02443735 0.70736911 0.3335518 ]
 [0.04729875 0.13849129 0.71293126 0.54512912 0.02398555 0.88920276
  0.79450355 0.19119055 0.13354262 0.8727707 ]
 [0.3092337  0.62712095 0.37471516 0.62546433 0.92028601 0.29994796
  0.41844992 0.85550456 0.56129109 0.10544303]
 [0.1848208  0.62519989 0.29934271 0.64204205 0.83171217 0.62717049
  0.08412513 0.07438677 0.39851364 0.39899278]
 [0.03243541 0.75484019 0.42597164 0.68793331 0.35292526 0.72879465
  0.6176