In [1]:
# Bonus problem. You get extra credit if you do this problem. Write a short program to implement
# the QR factorization of a matrix using Householder reflections. Your program should take as input A
# and return Q and R such that A = QR. Test your program on random matrices and explain how you
# performed the tests

In [2]:
import numpy as np

In [3]:
def qr(A):
    # Convert matrix to type float
    A = np.array(A, dtype=float)
    
    # Get dimensions of A
    m, n = A.shape
    runs = min(m-1, n)
    
    # Create the Q matrix, which begins as the identity
    Q = np.eye(m)
    
    # Go to m-1 because no need to apply on 1x1 matrix
    # If matrix is tall, i loops to n
    for i in range(runs):
        # Household vector
        a = np.array(A[i:,i])
        
        alpha = np.linalg.norm(a)
        alpha *= -np.sign(a[0])
        
        # Only applying alpha to the first elemenet is 
        # the same as multiplying alpha by the standard
        # basis vector and adding
        a[0] += alpha
        
        # The ith Householder matrix
        Qi = np.eye(m)
        sq_mag = (np.power(np.linalg.norm(a), 2))
        Qi[i:, i:] -= (2 / sq_mag * np.outer(a, a))
        
        # Multiply A with householder 
        # Makes i col of A to all zeros
        # Eventually will become upper right
        A = Qi @ A
        
        # Q is the multiplication of all the householder 
        # matrices transposed. Can multiply at each step
        Q = Q @ Qi.T
            
#     Q = np.round(Q, 10)
#     R = np.round(A, 10)
    R = A
    return Q, R

In [4]:
A = np.array([[1,3],
            [2,2]])
Q, R = qr(A)

print("Q:\n",Q)
print("R:\n",R)
print ("QR:\n",Q @ R)
print("A:\n",A)

print("Is Q orthonormal?",
      np.allclose(Q @ Q.T, np.eye(len(Q))))
print("Is R upper triangular?",
      np.allclose(R, np.triu(R)))

Q:
 [[ 0.4472136   0.89442719]
 [ 0.89442719 -0.4472136 ]]
R:
 [[ 2.23606798e+00  3.13049517e+00]
 [-1.11022302e-16  1.78885438e+00]]
QR:
 [[1. 3.]
 [2. 2.]]
A:
 [[1 3]
 [2 2]]
Is Q orthonormal? True
Is R upper triangular? True


In [5]:
A = np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
Q, R = qr(A)

print("Q:\n",Q)
print("R:\n",R)
print ("QR:\n",Q @ R)
print("A:\n",A)

print("Is Q orthonormal?",
      np.allclose(Q @ Q.T, np.eye(len(Q))))
print("Is R upper triangular?",
      np.allclose(R, np.triu(R)))

Q:
 [[ 0.12309149  0.90453403 -0.40824829]
 [ 0.49236596  0.30151134  0.81649658]
 [ 0.86164044 -0.30151134 -0.40824829]]
R:
 [[ 8.12403840e+00  9.60113630e+00  1.10782342e+01]
 [ 1.65195833e-15  9.04534034e-01  1.80906807e+00]
 [-8.58899047e-16  5.24723615e-17  1.12499203e-15]]
QR:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Is Q orthonormal? True
Is R upper triangular? True


In [6]:
A = np.random.randint(0, 99, (4,6))

Q, R = qr(A)

print("Q:\n",Q)
print("R:\n",R)
print ("QR:\n",Q @ R)
print("A:\n",A)

print("QR = A?", np.allclose(Q @ R, A))
print("Is Q orthonormal?",
      np.allclose(Q @ Q.T, np.eye(len(Q))))
print("Is R upper triangular?",
      np.allclose(R, np.triu(R)))

Q:
 [[ 0.70282933  0.41927275  0.34630259 -0.45860201]
 [ 0.58370571 -0.00632932 -0.11202784  0.80417495]
 [ 0.03573708  0.49350753 -0.85740956 -0.1414992 ]
 [ 0.40502029 -0.76198465 -0.36383118 -0.35066341]]
R:
 [[ 8.39464115e+01  8.26956135e+01  1.00552243e+02  6.08721673e+01
   7.48453673e+01  8.57809151e+01]
 [-8.71412155e-15  4.26431179e+01 -4.52412852e+01 -3.78457603e+01
   1.34046585e+01  3.47839151e+01]
 [-8.42327770e-15 -1.01596996e-14 -6.26695497e+01 -5.17951095e+01
  -5.35439365e+01 -9.39723613e+01]
 [ 1.46501620e-14  3.70002768e-15 -3.55927666e-15 -2.18527874e+01
  -2.68613661e+01  2.68869701e+01]]
QR:
 [[59. 76. 30. 19. 52. 30.]
 [49. 48. 66. 24. 28. 82.]
 [ 3. 24. 35. 31. 59. 97.]
 [34.  1. 98. 80. 49. 33.]]
A:
 [[59 76 30 19 52 30]
 [49 48 66 24 28 82]
 [ 3 24 35 31 59 97]
 [34  1 98 80 49 33]]
QR = A? True
Is Q orthonormal? True
Is R upper triangular? True


In [7]:
A = np.random.randint(0, 99, (6,4))
Q, R = qr(A)

print("Q:\n",Q)
print("R:\n",R)
print ("QR:\n",Q @ R)
print("A:\n",A)

print("QR = A?", np.allclose(Q @ R, A))
print("Is Q orthonormal?",
      np.allclose(Q @ Q.T, np.eye(len(Q))))
print("Is R upper triangular?",
      np.allclose(R, np.triu(R)))

Q:
 [[ 0.48488464  0.63029189 -0.34397612  0.46010553 -0.18791419 -0.04786029]
 [ 0.54993014 -0.11975623 -0.01099929 -0.12497658  0.78717602 -0.2187443 ]
 [ 0.10643809 -0.60990484  0.04496708  0.77045452 -0.00387898  0.14508537]
 [ 0.4316656  -0.19674118  0.42190435 -0.13545    -0.50514436 -0.56871514]
 [ 0.51445078 -0.16587515 -0.00809625 -0.34096982 -0.23542449  0.73217155]
 [ 0.01182645 -0.38753712 -0.83753721 -0.21089444 -0.18555756 -0.26324602]]
R:
 [[ 1.69112389e+02  1.35501604e+02  1.32716474e+02  1.62850281e+02]
 [-2.74632491e-14 -1.04241619e+02  3.69617455e+00 -5.16638717e+01]
 [ 1.12271338e-14 -1.84896077e-16 -4.16254215e+01 -7.66128830e+01]
 [-2.05593571e-14 -1.03372000e-14  3.17085201e-15  5.26981643e+01]
 [ 9.60604390e-15 -1.34099051e-14 -1.35787010e-15 -4.44089210e-16]
 [ 1.31074971e-14  5.92205893e-15  2.01898975e-15 -4.94049246e-15]]
QR:
 [[ 8.20000000e+01 -1.42108547e-14  8.10000000e+01  9.70000000e+01]
 [ 9.30000000e+01  8.70000000e+01  7.30000000e+01  9.00000000e+01]

In [8]:
for i in range(10):
    m = np.random.randint(1,99)
    n = np.random.randint(1,99)

    A = np.random.randint(0, 99, (m,n))
    Q, R = qr(A)

    print("m:",m,"n:",n)
    print("QR = A?", np.allclose(Q @ R, A))
    print("Is Q orthonormal?",
          np.allclose(Q @ Q.T, np.eye(len(Q))))
    print("Is R upper triangular?",
          np.allclose(R, np.triu(R)))
    if (i < 9):
        print()

m: 23 n: 66
QR = A? True
Is Q orthonormal? True
Is R upper triangular? True

m: 93 n: 31
QR = A? True
Is Q orthonormal? True
Is R upper triangular? True

m: 38 n: 3
QR = A? True
Is Q orthonormal? True
Is R upper triangular? True

m: 68 n: 93
QR = A? True
Is Q orthonormal? True
Is R upper triangular? True

m: 72 n: 80
QR = A? True
Is Q orthonormal? True
Is R upper triangular? True

m: 69 n: 76
QR = A? True
Is Q orthonormal? True
Is R upper triangular? True

m: 9 n: 1
QR = A? True
Is Q orthonormal? True
Is R upper triangular? True

m: 82 n: 45
QR = A? True
Is Q orthonormal? True
Is R upper triangular? True

m: 13 n: 80
QR = A? True
Is Q orthonormal? True
Is R upper triangular? True

m: 82 n: 17
QR = A? True
Is Q orthonormal? True
Is R upper triangular? True
