In [1]:
import numpy as np

def house(v):
    H = np.eye(len(v))
    H -= ((2/(np.linalg.norm(v)*np.linalg.norm(v)))*(np.outer(v,v)))
    return H

In [2]:
# Part A
A = np.array([[1,1,0],
              [1,0,2],
              [1,0,1],
              [1,1,-1]])
a = A[:,0]
e1 = np.array([1,0,0,0])
res = e1 * np.linalg.norm(a)
v = a - res

print("v:",v)

Hv = house(v)
B = Hv @ A
print("B:\n",B)

v: [-1.  1.  1.  1.]
B:
 [[ 2.  1.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  0.]
 [ 0.  1. -2.]]


In [3]:
# Part B
b = B[1:,1]

e1 = np.array([1,0,0])
res = e1 * np.linalg.norm(b)
u = b - res

print("u:",u)

Hu = house(u)
Hu = np.round(Hu, 10)

C = np.eye(len(Hu) + 1)
C[1:,1:] = Hu
Hu1 = C
C = C @ B
print("C:\n",C)

u: [-1.  0.  1.]
C:
 [[ 2.  1.  1.]
 [ 0.  1. -2.]
 [ 0.  0.  0.]
 [ 0.  0.  1.]]


In [4]:
# Part C
c = C[2:,2]

e1 = np.array([1,0])
res = e1 * np.linalg.norm(c)
w = c - res

print("w:",w)

Hw = house(w)
Hw = np.round(Hw, 10)

D = np.eye(len(Hw) + 2)
D[2:,2:] = Hw
Hw1 = D
D = D @ C
print("D:\n",D)

w: [-1.  1.]
D:
 [[ 2.  1.  1.]
 [ 0.  1. -2.]
 [ 0.  0.  1.]
 [ 0.  0.  0.]]


In [5]:
# Part D

# Hw1 is Hw but padded with a 2x2 identity matrix to the upper left 
# with the other entries in the rows and columns being zero
# Hu1 is Hu but padded with an upper left 1 and the other entries in 
# the columns and rows being zero
# Hv is just the original Hv matrix

R = Hw1 @ Hu1 @ Hv @ A
Q = Hw1 @ Hu1 @ Hv
Q = np.linalg.inv(Q)

print("A:\n",A)
print("QR:\n", Q @ R)
print("Q:\n",Q)
print("R:\n",R)

print("QR = A?", np.allclose(Q @ R, A))
print("Is Q orthonormal?",
      np.allclose(Q @ Q.T, np.eye(len(Q))))
print("Is R upper triangular?",
      np.allclose(R, np.triu(R)))

A:
 [[ 1  1  0]
 [ 1  0  2]
 [ 1  0  1]
 [ 1  1 -1]]
QR:
 [[ 1.  1.  0.]
 [ 1.  0.  2.]
 [ 1.  0.  1.]
 [ 1.  1. -1.]]
Q:
 [[ 0.5  0.5  0.5  0.5]
 [ 0.5 -0.5  0.5 -0.5]
 [ 0.5 -0.5 -0.5  0.5]
 [ 0.5  0.5 -0.5 -0.5]]
R:
 [[ 2.  1.  1.]
 [ 0.  1. -2.]
 [ 0.  0.  1.]
 [ 0.  0.  0.]]
QR = A? True
Is Q orthonormal? True
Is R upper triangular? True
